# Root directory for all input streams. This can be overridden as needed.
root: .

# Metadata about P-stream timestamps.
timezone: UTC
timestamp_grammar: |
  ISO-8601, HH:MM:SS[.ffffff], floating-point seconds since the Unix epoch,
  or Mxx-Dxx-Hxx-Mxx-Sxx-U.xxx

