# Root directories for input streams. These can be overridden as needed.
root:
  ostream: .
  pstream: .

# Paths to input streams relative to the roots above.
ostream: ${dataset.root.ostream}/sample_ostream.npz
pstream: ${dataset.root.pstream}/sample_pstream.txt

# Metadata about P-stream timestamps.
timezone: UTC
timestamp_grammar: |
  ISO-8601, HH:MM:SS[.ffffff], floating-point seconds since the Unix epoch,
  or Mxx-Dxx-Hxx-Mxx-Sxx-U.xxx

